"""
LLM-EvalHub Evaluation Engine

Supports:
1. Exact Match evaluation
2. Token F1 evaluation
3. TF-IDF + Cosine Similarity evaluation
4. Local deterministic evaluation
5. Gemini LLM-as-a-Judge evaluation

Important:
- Local scores are for pipeline validation and reproducible testing.
- Real LLM judge scores are generated by Gemini.
- Exact Match and Token F1 are deterministic reference-based metrics.
- TF-IDF cosine similarity is a lightweight lexical similarity baseline.
"""

import math
import re
from collections import Counter

from app.llm_judge import judge_response


# ============================================================
# SUPPORTED EVALUATION METRICS
# ============================================================

METRIC_DEFINITIONS = {

    "exact_match": (
        "Evaluate whether the normalized model answer exactly "
        "matches the expected answer."
    ),

    "token_f1": (
        "Evaluate token-level overlap between the model answer "
        "and expected answer using precision, recall, and F1."
    ),

    "tfidf_cosine_similarity": (
        "Measure similarity between the model answer and expected "
        "answer using TF-IDF weighted word vectors and cosine similarity."
    ),

    "correctness": (
        "Evaluate whether the answer is factually correct based "
        "on the expected answer."
    ),

    "relevance": (
        "Evaluate how directly and completely the answer addresses "
        "the question."
    ),

    "faithfulness": (
        "Evaluate whether the answer is supported by the supplied "
        "context and does not introduce unsupported claims."
    ),

    "coherence": (
        "Evaluate whether the answer is clear, logically structured, "
        "consistent, and easy to understand."
    ),

    "hallucination": (
        "Evaluate whether the answer contains fabricated or unsupported "
        "information."
    ),
}


# ============================================================
# DEFAULT STANDARD EVALUATION METRICS
# ============================================================

STANDARD_METRICS = [
    "exact_match",
    "token_f1",
    "tfidf_cosine_similarity",
    "correctness",
    "relevance",
    "faithfulness",
    "coherence",
]


# ============================================================
# SCORE VALIDATION
# ============================================================

def clamp_score(score):
    """
    Safely restrict a score to the range 0.0–1.0.
    """

    if score is None:
        return None

    try:
        value = float(score)

        if math.isnan(value) or math.isinf(value):
            return None

        return max(
            0.0,
            min(1.0, value)
        )

    except (TypeError, ValueError):
        return None


# ============================================================
# TEXT NORMALIZATION
# ============================================================

def _normalise_words(text):
    """
    Convert text into a normalized set of words.

    Used by lightweight local evaluation metrics.
    """

    if not text:
        return set()

    cleaned = (
        str(text)
        .lower()
        .replace(".", " ")
        .replace(",", " ")
        .replace("?", " ")
        .replace("!", " ")
        .replace(":", " ")
        .replace(";", " ")
        .replace("(", " ")
        .replace(")", " ")
        .replace("[", " ")
        .replace("]", " ")
        .replace("{", " ")
        .replace("}", " ")
        .replace('"', " ")
        .replace("'", " ")
    )

    return {
        word
        for word in cleaned.split()
        if len(word) > 2
    }


# ============================================================
# TOKENIZATION FOR TF-IDF
# ============================================================

def _tokenize_for_tfidf(text):
    """
    Tokenize text for the lightweight TF-IDF implementation.
    """

    if not text:
        return []

    tokens = re.findall(
        r"\b[a-zA-Z0-9]+\b",
        str(text).lower()
    )

    return [
        token
        for token in tokens
        if len(token) > 2
    ]


# ============================================================
# TF-IDF VECTOR
# ============================================================

def _tfidf_vectors(text_a, text_b):
    """
    Build TF-IDF vectors for two documents.
    """

    tokens_a = _tokenize_for_tfidf(text_a)
    tokens_b = _tokenize_for_tfidf(text_b)

    if not tokens_a or not tokens_b:
        return None, None

    documents = [
        tokens_a,
        tokens_b,
    ]

    vocabulary = sorted(
        set(tokens_a) | set(tokens_b)
    )

    document_count = len(documents)

    document_frequency = {}

    for term in vocabulary:
        document_frequency[term] = sum(
            1
            for document in documents
            if term in document
        )

    vectors = []

    for tokens in documents:

        counts = Counter(tokens)
        total_terms = len(tokens)

        vector = []

        for term in vocabulary:

            tf = (
                counts[term]
                / total_terms
            )

            df = document_frequency[term]

            idf = (
                math.log(
                    (document_count + 1)
                    / (df + 1)
                )
                + 1.0
            )

            vector.append(
                tf * idf
            )

        vectors.append(vector)

    return vectors[0], vectors[1]


# ============================================================
# COSINE SIMILARITY
# ============================================================

def _cosine_similarity(vector_a, vector_b):
    """
    Calculate cosine similarity between two numeric vectors.
    """

    if not vector_a or not vector_b:
        return 0.0

    dot_product = sum(
        a * b
        for a, b in zip(
            vector_a,
            vector_b
        )
    )

    magnitude_a = math.sqrt(
        sum(
            value * value
            for value in vector_a
        )
    )

    magnitude_b = math.sqrt(
        sum(
            value * value
            for value in vector_b
        )
    )

    if magnitude_a == 0.0 or magnitude_b == 0.0:
        return 0.0

    similarity = (
        dot_product
        / (magnitude_a * magnitude_b)
    )

    return clamp_score(similarity) or 0.0


# ============================================================
# TF-IDF COSINE SIMILARITY
# ============================================================

def tfidf_cosine_similarity_score(
    answer: str,
    expected: str,
) -> dict:
    """
    Calculate TF-IDF weighted cosine similarity.
    """

    if not expected or not expected.strip():

        return {
            "score": None,
            "explanation": (
                "No expected answer was supplied, so TF-IDF cosine "
                "similarity cannot be calculated."
            ),
        }

    if not answer or not answer.strip():

        return {
            "score": 0.0,
            "explanation": (
                "The model answer is empty."
            ),
        }

    vector_a, vector_b = _tfidf_vectors(
        answer,
        expected,
    )

    if vector_a is None or vector_b is None:

        return {
            "score": 0.0,
            "explanation": (
                "Insufficient textual content was available "
                "to calculate TF-IDF similarity."
            ),
        }

    score = _cosine_similarity(
        vector_a,
        vector_b,
    )

    return {
        "score": score,
        "explanation": (
            "TF-IDF weighted cosine similarity between the "
            "model answer and expected answer."
        ),
    }


# ============================================================
# EXACT MATCH
# ============================================================

def exact_match_score(
    answer: str,
    expected: str,
) -> dict:
    """
    Calculate normalized Exact Match.
    """

    if not expected or not expected.strip():

        return {
            "score": None,
            "explanation": (
                "No expected answer was supplied, so exact match "
                "cannot be calculated."
            ),
        }

    answer_clean = " ".join(
        str(answer).lower().split()
    )

    expected_clean = " ".join(
        str(expected).lower().split()
    )

    if answer_clean == expected_clean:

        return {
            "score": 1.0,
            "explanation": (
                "The normalized model answer exactly matches "
                "the expected answer."
            ),
        }

    return {
        "score": 0.0,
        "explanation": (
            "The normalized model answer does not exactly match "
            "the expected answer."
        ),
    }


# ============================================================
# TOKEN F1
# ============================================================

def token_f1_score(
    answer: str,
    expected: str,
) -> dict:
    """
    Calculate token-level F1 score.
    """

    if not expected or not expected.strip():

        return {
            "score": None,
            "explanation": (
                "No expected answer was supplied, so token F1 "
                "cannot be calculated."
            ),
        }

    answer_tokens = str(answer).lower().split()
    expected_tokens = str(expected).lower().split()

    if not answer_tokens:

        return {
            "score": 0.0,
            "explanation": (
                "The model answer is empty."
            ),
        }

    if not expected_tokens:

        return {
            "score": None,
            "explanation": (
                "The expected answer is empty."
            ),
        }

    answer_counts = Counter(
        answer_tokens
    )

    expected_counts = Counter(
        expected_tokens
    )

    common_tokens = (
        answer_counts
        & expected_counts
    )

    overlap = sum(
        common_tokens.values()
    )

    if overlap == 0:

        return {
            "score": 0.0,
            "explanation": (
                "No overlapping tokens were found between "
                "the model answer and expected answer."
            ),
        }

    precision = (
        overlap
        / len(answer_tokens)
    )

    recall = (
        overlap
        / len(expected_tokens)
    )

    if precision + recall == 0:

        f1 = 0.0

    else:

        f1 = (
            2
            * precision
            * recall
            / (precision + recall)
        )

    return {
        "score": clamp_score(f1),
        "explanation": (
            f"Token F1 based on precision={precision:.3f} "
            f"and recall={recall:.3f}."
        ),
    }


# ============================================================
# LOCAL DETERMINISTIC EVALUATOR
# ============================================================

def local_score(
    question: str,
    answer: str,
    metric: str,
    context: str = "",
    expected: str = "",
) -> dict:
    """
    Deterministic local evaluator.

    Used for mock-model experiments and pipeline testing.

    These scores are NOT benchmark-quality LLM evaluation results.
    """

    # --------------------------------------------------------
    # CORRECTNESS
    # --------------------------------------------------------

    if metric == "correctness":

        if not expected.strip():

            return {
                "score": 0.5,
                "explanation": (
                    "No expected answer was supplied, so correctness "
                    "cannot be fully assessed in local test mode."
                ),
            }

        answer_clean = answer.strip().lower()
        expected_clean = expected.strip().lower()

        if answer_clean == expected_clean:

            return {
                "score": 1.0,
                "explanation": (
                    "The answer exactly matches the expected answer "
                    "in local test mode."
                ),
            }

        expected_words = _normalise_words(
            expected
        )

        answer_words = _normalise_words(
            answer
        )

        if expected_words:

            overlap = (
                expected_words.intersection(
                    answer_words
                )
            )

            similarity = (
                len(overlap)
                / len(expected_words)
            )

            return {
                "score": clamp_score(similarity),
                "explanation": (
                    "The local evaluator estimated correctness "
                    "using word overlap with the expected answer."
                ),
            }

        return {
            "score": 0.0,
            "explanation": (
                "The answer does not match the expected answer "
                "in local test mode."
            ),
        }

    # --------------------------------------------------------
    # RELEVANCE
    # --------------------------------------------------------

    if metric == "relevance":

        question_words = _normalise_words(
            question
        )

        answer_words = _normalise_words(
            answer
        )

        if not question_words or not answer_words:

            return {
                "score": 0.0,
                "explanation": (
                    "The question or answer contains insufficient "
                    "text for the local relevance check."
                ),
            }

        overlap = (
            question_words.intersection(
                answer_words
            )
        )

        if overlap:

            score = min(
                1.0,
                len(overlap)
                / max(
                    1,
                    len(question_words)
                ),
            )

            return {
                "score": score,
                "explanation": (
                    "The local evaluator detected overlap between "
                    "question and answer terms."
                ),
            }

        return {
            "score": 0.0,
            "explanation": (
                "No meaningful question-answer word overlap was "
                "detected by the local heuristic."
            ),
        }

    # --------------------------------------------------------
    # FAITHFULNESS
    # --------------------------------------------------------

    if metric == "faithfulness":

        if not context.strip():

            return {
                "score": 0.5,
                "explanation": (
                    "No reference context was supplied, so faithfulness "
                    "cannot be fully assessed in local test mode."
                ),
            }

        context_words = _normalise_words(
            context
        )

        answer_words = _normalise_words(
            answer
        )

        if not answer_words:

            return {
                "score": 0.0,
                "explanation": (
                    "The model answer is empty."
                ),
            }

        overlap = (
            context_words.intersection(
                answer_words
            )
        )

        score = (
            len(overlap)
            / len(answer_words)
        )

        return {
            "score": clamp_score(score),
            "explanation": (
                "The local evaluator estimated faithfulness "
                "using answer-context word overlap."
            ),
        }

    # --------------------------------------------------------
    # COHERENCE
    # --------------------------------------------------------

    if metric == "coherence":

        if not answer.strip():

            return {
                "score": 0.0,
                "explanation": (
                    "The model answer is empty."
                ),
            }

        words = answer.split()

        if len(words) == 1:

            return {
                "score": 0.5,
                "explanation": (
                    "The answer is non-empty but very short, so "
                    "the local coherence estimate is limited."
                ),
            }

        return {
            "score": 1.0,
            "explanation": (
                "The answer is non-empty and passes the basic "
                "local coherence validation."
            ),
        }

    # --------------------------------------------------------
    # HALLUCINATION
    # --------------------------------------------------------

    if metric == "hallucination":

        if not context.strip():

            return {
                "score": 0.5,
                "explanation": (
                    "No reference context was supplied, so hallucination "
                    "cannot be reliably assessed in local test mode."
                ),
            }

        context_words = _normalise_words(
            context
        )

        answer_words = _normalise_words(
            answer
        )

        if not answer_words:

            return {
                "score": 1.0,
                "explanation": (
                    "The answer contains no claims because it is empty."
                ),
            }

        supported_words = (
            context_words.intersection(
                answer_words
            )
        )

        support_ratio = (
            len(supported_words)
            / len(answer_words)
        )

        return {
            "score": clamp_score(support_ratio),
            "explanation": (
                "The local evaluator estimated hallucination risk "
                "using overlap between answer and reference context."
            ),
        }

    raise ValueError(
        f"Unsupported evaluation metric: {metric}"
    )


# ============================================================
# GEMINI LLM-AS-A-JUDGE
# ============================================================

def judge_score(
    question: str,
    answer: str,
    metric: str,
    context: str = "",
    expected: str = "",
) -> dict:
    """
    Evaluate one metric using the shared Gemini LLM-as-a-Judge.

    The actual Gemini judge is implemented in app.llm_judge.

    This function extracts the requested metric from the complete
    five-metric judge result.
    """

    if metric not in METRIC_DEFINITIONS:
        raise ValueError(
            f"Unsupported evaluation metric: {metric}"
        )

    judge_result = judge_response(
        question=question,
        context=context,
        expected_answer=expected,
        model_answer=answer,
    )

    score = clamp_score(
        judge_result.get(metric)
    )

    explanations = judge_result.get(
        "explanations",
        {}
    )

    explanation = explanations.get(
        metric,
        "No explanation provided by the Gemini judge."
    )

    # Add useful information about fallback status.
    if judge_result.get("fallback"):
        explanation = (
            f"{explanation} "
            "WARNING: deterministic local fallback was used."
        )

    return {
        "score": score,
        "explanation": explanation,
    }


# ============================================================
# MAIN EVALUATION PIPELINE
# ============================================================

def evaluate_response(
    question: str,
    answer: str,
    context: str = "",
    expected: str = "",
    metrics=None,
    model_name: str = "",
) -> list[dict]:
    """
    Evaluate one model response.

    By default, exactly 7 standard metrics are evaluated:

    1. exact_match
    2. token_f1
    3. tfidf_cosine_similarity
    4. correctness
    5. relevance
    6. faithfulness
    7. coherence

    Returns one dictionary per metric.
    """

    # --------------------------------------------------------
    # DEFAULT METRICS
    # --------------------------------------------------------

    if metrics is None:

        metrics = STANDARD_METRICS.copy()

    else:

        metrics = list(metrics)

    # --------------------------------------------------------
    # VALIDATE METRICS
    # --------------------------------------------------------

    for metric in metrics:

        if metric not in METRIC_DEFINITIONS:

            raise ValueError(
                f"Unsupported evaluation metric: {metric}"
            )

    # --------------------------------------------------------
    # EVALUATION RESULTS
    # --------------------------------------------------------

    results = []

    for metric in metrics:

        # ====================================================
        # EXACT MATCH
        # ====================================================

        if metric == "exact_match":

            result = exact_match_score(
                answer=answer,
                expected=expected,
            )

        # ====================================================
        # TOKEN F1
        # ====================================================

        elif metric == "token_f1":

            result = token_f1_score(
                answer=answer,
                expected=expected,
            )

        # ====================================================
        # TF-IDF COSINE SIMILARITY
        # ====================================================

        elif metric == "tfidf_cosine_similarity":

            result = tfidf_cosine_similarity_score(
                answer=answer,
                expected=expected,
            )

        # ====================================================
        # MOCK MODEL
        # ====================================================

        elif model_name.strip().lower() == "mock-model":

            result = local_score(
                question=question,
                answer=answer,
                metric=metric,
                context=context,
                expected=expected,
            )

        # ====================================================
        # REAL MODEL
        # ====================================================

        else:

            result = judge_score(
                question=question,
                answer=answer,
                metric=metric,
                context=context,
                expected=expected,
            )

        # ----------------------------------------------------
        # GUARANTEE RESULT STRUCTURE
        # ----------------------------------------------------

        if not isinstance(result, dict):

            result = {
                "score": None,
                "explanation": (
                    "The evaluator returned an invalid result."
                ),
            }

        score = clamp_score(
            result.get("score")
        )

        explanation = result.get(
            "explanation"
        )

        # ----------------------------------------------------
        # ALWAYS RETURN METRIC RECORD
        # ----------------------------------------------------

        results.append(
            {
                "metric_name": metric,
                "score_value": score,
                "explanation": explanation,
            }
        )

    return results


# ============================================================
# SIMPLE SELF-TEST
# ============================================================

if __name__ == "__main__":

    print("\nLLM-EvalHub evaluator self-test")
    print("=" * 60)

    # Test the objective metrics separately.
    test_results = evaluate_response(
        question="What is machine learning?",
        answer=(
            "Machine learning enables systems to learn "
            "patterns from data."
        ),
        context=(
            "Machine learning is a branch of artificial intelligence "
            "that enables systems to learn patterns from data."
        ),
        expected=(
            "Machine learning enables systems to learn patterns "
            "from data."
        ),
        model_name="mock-model",
    )

    print(
        f"Expected metric count: {len(STANDARD_METRICS)}"
    )

    print(
        f"Actual metric count:   {len(test_results)}"
    )

    print()

    for item in test_results:

        print(
            f"{item['metric_name']}: "
            f"{item['score_value']}"
        )

    print()

    if len(test_results) == 7:
        print(
            "PASS: All 7 standard metrics were generated."
        )
    else:
        print(
            "FAIL: Standard metric count is not 7."
        )

    # --------------------------------------------------------
    # REAL GEMINI JUDGE TEST
    # --------------------------------------------------------

    print()
    print("=" * 60)
    print("Gemini LLM-as-a-Judge integration test")
    print("=" * 60)

    judge_test = judge_response(
        question="What is machine learning?",
        context=(
            "Machine learning is a branch of artificial intelligence "
            "that enables systems to learn patterns from data."
        ),
        expected_answer=(
            "Machine learning enables systems to learn patterns "
            "from data."
        ),
        model_answer=(
            "Machine learning enables computers to learn patterns "
            "from data and make predictions."
        ),
    )

    print(
        f"Judge type   : {judge_test.get('judge_type')}"
    )

    print(
        f"Judge model  : {judge_test.get('judge_model')}"
    )

    print(
        f"Rubric       : {judge_test.get('rubric_version')}"
    )

    print(
        f"Fallback     : {judge_test.get('fallback')}"
    )

    if judge_test.get("fallback"):
        print(
            f"Reason       : {judge_test.get('fallback_reason')}"
        )
    else:
        print(
            "Status       : REAL GEMINI LLM JUDGE"
        )

    print("=" * 60)